//
// Created by Sona on 5/2/2026 AD.
//

#ifndef IOT_LAITTEIDEN_C_OHJELMOINTI_RUN_EXERCIS5E_5_H
#define IOT_LAITTEIDEN_C_OHJELMOINTI_RUN_EXERCIS5E_5_H

#endif //IOT_LAITTEIDEN_C_OHJELMOINTI_RUN_EXERCIS5E_5_H